#### 📝 Load environment variables and project configurations | 🏗️ CBOT PROJECT

In [1]:
import sys
import os
from pathlib import Path
from dotenv import load_dotenv

PROJECT_ROOT = Path("/home/xtallet/inari/inari-henzuru-data")
ENV_PATH = PROJECT_ROOT / ".env"

load_dotenv(dotenv_path=ENV_PATH)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from app.config.settings import AzureOpenAIConfig, LangSmithConfig

cfg = AzureOpenAIConfig()
ls_cfg = LangSmithConfig()

print("Azure & LangSmith config loaded")

Azure & LangSmith config loaded

#### 📝 Print LangSmith environment variables | 🏗️ CBOT PROJECT

In [2]:
print(f"LANGSMITH_ENDPOINT: {os.getenv('LANGSMITH_ENDPOINT')}")
print(f"LANGSMITH_PROJECT: {os.getenv('LANGSMITH_PROJECT')}")

LANGSMITH_ENDPOINT: https://eu.api.smith.langchain.com
LANGSMITH_PROJECT: ChatBot-Project-Evaluations

#### 📝 Configure LangSmith environment for tracing | 🏗️ CBOT PROJECT

In [3]:
os.environ["LANGSMITH_TRACING"] = "true" if getattr(ls_cfg, "LANGSMITH_TRACING", True) else "false"
os.environ["LANGSMITH_API_KEY"] = ls_cfg.LANGSMITH_API_KEY
os.environ["LANGSMITH_ENDPOINT"] = ls_cfg.LANGSMITH_ENDPOINT
os.environ["LANGSMITH_PROJECT"] = ls_cfg.LANGSMITH_PROJECT

print("LangSmith listo para trazar")

LangSmith listo para trazar

#### 📝 Display Azure OpenAI configuration with masked API key | 🏗️ CBOT PROJECT

In [4]:
def _mask(value: str, show: int = 4) -> str:
    if not value:
        return value
    return value[:show] + "..." + value[-show:]

print("Endpoint:", cfg.AZURE_OPENAI_API_ENDPOINT)
print("API version:", cfg.AZURE_OPENAI_API_VERSION)
print("LLM deployment:", cfg.AZURE_OPENAI_LLM_DEPLOYMENT_NAME)
print("Embedding deployment:", cfg.AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME)
print("API key:", _mask(cfg.AZURE_OPENAI_API_KEY))

Endpoint: https://inari-yomeru.openai.azure.com/
API version: 2024-12-01-preview
LLM deployment: inari-yomeru-gpt-4.1
Embedding deployment: inari-yomeru-embedding
API key: 858d...87c3

#### 📝 Initialize Azure OpenAI client | 🏗️ CBOT PROJECT

In [5]:
from openai import AzureOpenAI

client = AzureOpenAI(
    api_key=cfg.AZURE_OPENAI_API_KEY,
    azure_endpoint=cfg.AZURE_OPENAI_API_ENDPOINT,
    api_version=cfg.AZURE_OPENAI_API_VERSION,
)
print("Azure OpenAI client ready")

Azure OpenAI client ready

#### 📝 Import libraries for dataset generation and evaluation | 🏗️ CBOT PROJECT

In [6]:
import json
import pandas as pd
from langchain.text_splitter import RecursiveCharacterTextSplitter
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from ragas.testset import TestsetGenerator
from ragas import evaluate
from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall

#### 📝 Load real JSON dataset and convert to DataFrame | 🏗️ CBOT PROJECT

In [7]:
with open("datasets/evaluate_responses.json", "r", encoding="utf-8") as f:
    data = json.load(f)

golden_real = []
for item in data:
    golden_real.append({
        "question": item["input"],
        "answer": item["nl_output"],
        "contexts": [item["sql_response"]]
    })

df_real = pd.DataFrame(golden_real)
print(f"Real Golden Dataset: {len(df_real)} entries")

Real Golden Dataset: 26 entries

In [8]:
df_real.to_csv("kitsune_df_real.csv", index=False)

#### 📝 Print each entry from the real dataset | 🏗️ CBOT PROJECT

In [9]:
for entry in golden_real:
    print(f'entry : {entry}')

entry : {'question': 'Which policy has the highest premium in our portfolio?', 'answer': 'The policies DE2500169/R01 and DE2400169 both have the highest premium in your portfolio, which is 84,274,527,852.00.', 'contexts': ['policy_reference,status_group,premium,row_num DE2500169/R01,not_written,84274527852.0000000,1 DE2400169,written,84274527852.0000000,1']}
entry : {'question': 'Which policy has the lowest premium in our portfolio?', 'answer': 'The policy with the lowest premium in your portfolio is DE2100126, with a premium of 1.00.', 'contexts': ['policy_reference,premium DE2100126,1.0000000']}
entry : {'question': 'What is the average premium per policy in the portfolio?', 'answer': 'What is the average premium per policy in the portfolio?', 'contexts': ['policy_reference,premium_average,DE2100095,66.0000000000000000,DE2100098,1400000.000000000000,DE2100111,None,DE2100126,1.00000000000000000000,DE2100130,1.00000000000000000000,DE2100131,9.0000000000000000,DE2100200,None,DE2100201,None,DE2100221,600000.000000000000,DE2300051,5000.0000000000000000,DE2300071,200000.000000000000,DE2300100,None,DE2300102,None,DE2300108,None,DE2300109,None,DE2300110,None,DE2300111,10000.0000000000000000,DE2300115,10000.0000000000000000,DE2300116,None,DE2300119,None,DE2300120,5050000.000000000000,DE2300121,500000000.00000000,DE2300122,10000000.000000000000,DE2300123,30000.000000000000,DE2300124,200000.000000000000,DE2300132,200000.000000000000,DE2300133,30000.000000000000,DE2300134,None,DE2300135,30000.000000000000,DE2300136,50000.000000000000,DE2300137,40000.000000000000,DE2300138,30000.000000000000,DE2300139,15000.0000000000000000,DE2300140,10000.0000000000000000,DE2300141,60000.000000000000,DE2300142,50000.000000000000,DE2300143,10000.0000000000000000,DE2300146,10000000.000000000000,DE2300147,200000.000000000000,DE2300159,None,DE2300174,250000.000000000000,DE2300176,10000.0000000000000000,DE2300178,300000.000000000000,DE2300187,90000.000000000000,DE2300188,100000.000000000000,DE2300210,None,DE2300212,100000.000000000000,DE2300213,None,DE2300214,200000.000000000000,DE2300215,1200000.000000000000,DE2300223,100000.000000000000,DE2300229,100000.000000000000,DE2300234,10000000.000000000000,DE2300235,2000000.000000000000,DE2300240,500000.000000000000,DE2300253,None,DE2400038,2000000.000000000000,DE2400039,600000.000000000000,DE2400041,None,DE2400042,15000.0000000000000000,DE2400043,50000.000000000000,DE2400044,None,DE2400046,50000.000000000000,DE2400047,2000000.000000000000,DE2400047/R01,589000000.00000000,DE2400048,455877.000000000000,DE2400049,500000.000000000000,DE2400050,60000.000000000000,DE2400051,55000.000000000000,DE2400052,5000000.000000000000,DE2400054,60000.000000000000,DE2400055,25000.000000000000,DE2400056,50000.000000000000,DE2400057,15000000.000000000000,DE2400058,1000000.000000000000,DE2400059,None,DE2400060,None,DE2400061,None,DE2400062,150000.000000000000,DE2400063,100000.000000000000,DE2400064,100000.000000000000,DE2400065,150000.000000000000,DE2400066,None,DE2400067,None,DE2400068,None,DE2400070,110000.000000000000,DE2400071/R01,200000.000000000000,DE2400072,100000.000000000000,DE2400074,None,DE2400075,2000000.000000000000,DE2400076,None,DE2400077,1000000.000000000000,DE2400078,600000.000000000000,DE2400079,500000.000000000000,DE2400080,25000.000000000000,DE2400081,None,DE2400082,100000.000000000000,DE2400083,100000.000000000000,DE2400084,100000.000000000000,DE2400085,3000000.000000000000,DE2400086,150000.000000000000,DE2400088,None,DE2400090,4000000.000000000000,DE2400091,1000000.000000000000,DE2400098,None,DE2400102,1100000.000000000000,DE2400103,None,DE2400104,400000.000000000000,DE2400106,200000.000000000000,DE2400107,1000000.000000000000,DE2400109,None,DE2400110,None,DE2400117,None,DE2400124,None,DE2400126/R01,1.00000000000000000000,DE2400129,None,DE2400131,30000000.000000000000,DE2400132,50000.000000000000,DE2400133,None,DE2400134,6.0000000000000000,DE2400135,20000.000000000000,DE2400136,35000.000000000000,DE2400137,600000.000000000000,DE2400138,None,DE2400139,30000.000000000000,DE2400140,None,DE2400143,87000.000000000000,DE2400144,None,DE2400145,525000.000000000000,DE2400148,None,DE2400149,None,DE2400150,None,DE2400151,None,DE2400152,None,DE2400153,None,DE2400154,None,DE2400155,None,DE2400156,100000.000000000000,DE2400157,100000.000000000000,DE2400158,None,DE2400159,564654654.00000000,DE2400160,200000.000000000000,DE2400161,200000.000000000000,DE2400162,1.00000000000000000000,DE2400163,None,DE2400164,None,DE2400165,None,DE2400166,None,DE2400167,None,DE2400168,None,DE2400169,84274527852.00000000,DE2400170,None,DE2400171,50000.000000000000,DE2400172,50000.000000000000,DE2400173,1000000.000000000000,DE2400180,None,DE2400182,None,DE2400185,None,DE2400193,150000.000000000000,DE2400194,2500.0000000000000000,DE2400224,None,DE2400226,None,DE2400227,None,DE2400249,None,DE2500093,100000.000000000000,DE2500134,None,DE2500161/R01,200000.000000000000,DE2500162/R01,1.00000000000000000000,DE2500165,None,DE2500166,None,DE2500169,2500000000.00000000,DE2500169/R01,84274527852.00000000,DE2500170,414141414.00000000,DE2500171,4100000.000000000000,DE2500172,None,DE2500175,None,DE2500177,None,DE2500179,3000.0000000000000000,DE2500181,130000.000000000000,DE2500183,None,DE2500184,60000.000000000000,DE2500186,None,DE2500189,None,DE2500190,None,DE2500191,100000.000000000000,DE2500192,12.0000000000000000,DE2500195,1.00000000000000000000,DE2500196,50000.000000000000,DE2500197,40000.000000000000,DE2500198,1500000.000000000000,DE2500199,700000.000000000000,DE2500202,30000.000000000000,DE2500203,None,DE2500204,None,DE2500205,150000.000000000000,DE2500206,120000.000000000000,DE2500207,None,DE2500208,None,DE2500209,None,DE2500211,15000.0000000000000000,DE2500216,None,DE2500217,None,DE2500218,None,DE2500219,None,DE2500220,10000.0000000000000000,DE2500222,None,DE2500225,None,DE2500228,150000.000000000000,DE2500228/R01,150000.000000000000,DE2500230,65000.000000000000,DE2500231,None,DE2500232,40000.000000000000,DE2500233,None,DE2500236,None,DE2500237,None,DE2500238,None,DE2500239,50000.000000000000,DE2500241,None,DE2500242,None,DE2500243,None,DE2500244,None,DE2500245,50000.000000000000,DE2500246,2000000.000000000000,DE2500247,120000.000000000000,DE2500248,50000.000000000000,DE2500250,8000000.000000000000,DE2500251,None,DE2500252,None,S.2300002,35000.000000000000,S.2300003,25000.000000000000,S.2300007,100000.000000000000,S.2300008,120000.000000000000,S.2400001,90000.000000000000,S.2400004,None,S.2400005,None,S.2400006,25000.000000000000,S.2400009,60000.000000000000,S.2400010,None,S.2400011,None,S.2400012,870790.000000000000,S.2400013,None,S.2400014,55000.000000000000,S.2400015,45000.000000000000,S.2400016,30000.000000000000,S.2400017,90000.000000000000,S.2400018,25000.000000000000,S.2400019,150000.000000000000,S.2400020,30000.000000000000,S.2400021,None,S.2400022,None,S.2400023,None,S.2400026,4400000.000000000000,S.2400027,50000.000000000000,S.2400028,4400000.000000000000,S.2400029,2000000.000000000000,S.2400030,2000000.000000000000,S.2400031,90000.000000000000,S.2400032,10000000.000000000000,S.2400035,50000.000000000000,S.2400036,35000.000000000000']}
entry : {'question': 'What is the highest premium policy in Aviation', 'answer': 'The highest premium policy in Aviation is policy DE2400169 with a premium of 84,274,527,852.00.', 'contexts': ['policy_reference,status_group,line_of_business,premium DE2400169,written,Aviation,84274527852.0000000']}
entry : {'question': 'What is the average premium for policies in the segment Agriculture ?', 'answer': 'The average premium for policies in the segment Agriculture is 2,000,000.00.', 'contexts': ['average_premium 2000000.000000000000']}
entry : {'question': 'What is the average premium for policies with [a specific coverage type]?', 'answer': "I don't have the information to answer that question.", 'contexts': ['average_premium None']}
entry : {'question': 'Can you list the top 10 policies by premium amount?', 'answer': 'The top 10 policies by premium amount are DE2500169/R01, DE2400169, DE2500169, DE2400047/R01, DE2400159, DE2300121, DE2500170, DE2400131, DE2400057, and DE2300146.', 'contexts': ['']}
entry : {'question': 'What is the total premium collected for 2025-02-01 and 2025-02-17?', 'answer': 'The total premium collected for 2025-02-01 and 2025-02-17 is 190,000.', 'contexts': ['total premium for a given time of period190000.0000000']}
entry : {'question': 'What is the highest premium policy in UK?', 'answer': "I don't have the information to answer that question.", 'contexts': ['REVIEW - ERROR']}
entry : {'question': 'What is the premium trend over the last years?', 'answer': 'The premium trend over the last years shows significant fluctuations, with periods of rapid growth and sharp declines in both written and not written policies.', 'contexts': ['period,status_group,gross_premium,previous_gross_premium,gross_premium_growth,growth_percentage,2024-05-01 00:00:00+00:00,written,330000.0000000,None,None,None,2024-05-01 00:00:00+00:00,not_written,1150790.0000000,None,None,None,2024-06-01 00:00:00+00:00,written,9035000.0000000,330000.0000000,8705000.0000000,2637.88,2024-06-01 00:00:00+00:00,not_written,16450000.0000000,1150790.0000000,15299210.0000000,1329.45,2024-07-01 00:00:00+00:00,written,594220000.0000000,9035000.0000000,585185000.0000000,6476.87,2024-07-01 00:00:00+00:00,not_written,2050000.0000000,16450000.0000000,-14400000.0000000,-87.54,2024-08-01 00:00:00+00:00,written,1435000.0000000,594220000.0000000,-592785000.0000000,-99.76,2024-09-01 00:00:00+00:00,not_written,210000.0000000,2050000.0000000,-1840000.0000000,-89.76,2024-09-01 00:00:00+00:00,written,4025000.0000000,1435000.0000000,2590000.0000000,180.49,2024-10-01 00:00:00+00:00,written,36285077.0000000,4025000.0000000,32260077.0000000,801.49,2024-10-01 00:00:00+00:00,not_written,5010000.0000000,210000.0000000,4800000.0000000,2285.71,2024-11-01 00:00:00+00:00,written,41092000.0000000,36285077.0000000,4806923.0000000,13.25,2024-12-01 00:00:00+00:00,written,84839182507.0000000,41092000.0000000,84798090507.0000000,206361.56,2024-12-01 00:00:00+00:00,not_written,200000.0000000,5010000.0000000,-4810000.0000000,-96.01,2025-01-01 00:00:00+00:00,written,2918341414.0000000,84839182507.0000000,-81920841093.0000000,-96.56,2025-02-01 00:00:00+00:00,not_written,60000.0000000,200000.0000000,-140000.0000000,-70.00,2025-02-01 00:00:00+00:00,written,130000.0000000,2918341414.0000000,-2918211414.0000000,-100.00,2025-03-01 00:00:00+00:00,written,4350013.0000000,130000.0000000,4220013.0000000,3246.16,2025-03-01 00:00:00+00:00,not_written,32500.0000000,60000.0000000,-27500.0000000,-45.83,2025-04-01 00:00:00+00:00,not_written,65000.0000000,32500.0000000,32500.0000000,100.00,2025-04-01 00:00:00+00:00,written,10150000.0000000,4350013.0000000,5799987.0000000,133.33,2025-05-01 00:00:00+00:00,written,4100000.0000000,10150000.0000000,-6050000.0000000,-59.61,2025-06-01 00:00:00+00:00,written,8220000.0000000,4100000.0000000,4120000.0000000,100.49,None,not_written,84782971737.0000000,65000.0000000,84782906737.0000000,130435241.13']}
entry : {'question': 'Can you show premium growth by policy type?', 'answer': "Premium growth by policy type shows large fluctuations, particularly in 'direct' policies with periods of rapid increases and steep declines, while 'facultative-reinsurance' and 'co-insurance' types have smaller and more stable changes.", 'contexts': ['month,status_group,policy_type,gross_premium,previous_gross_premium,gross_premium_growth,growth_percentage;2021-07-01 00:00:00+00:00,written,direct,600077.0000000,None,None,None;2021-07-01 00:00:00+00:00,not_written,direct,1400000.0000000,None,None,None;2021-12-01 00:00:00+00:00,not_written,direct,None,1400000.0000000,None,None;2023-01-01 00:00:00+00:00,written,direct,50000.0000000,600077.0000000,-550077.0000000,-91.67;2023-01-01 00:00:00+00:00,not_written,direct,35000.0000000,None,None,None;2023-05-01 00:00:00+00:00,written,facultative-reinsurance,120000.0000000,None,None,None;2023-06-01 00:00:00+00:00,not_written,direct,125000.0000000,35000.0000000,90000.0000000,257.14;2023-07-01 00:00:00+00:00,not_written,direct,501310000.0000000,125000.0000000,501185000.0000000,400948.00;2023-07-01 00:00:00+00:00,written,direct,39370000.0000000,50000.0000000,39320000.0000000,78640.00;2023-10-01 00:00:00+00:00,written,direct,200000.0000000,39370000.0000000,-39170000.0000000,-99.49;2023-12-01 00:00:00+00:00,not_written,direct,250000.0000000,501310000.0000000,-501060000.0000000,-99.95;2024-01-01 00:00:00+00:00,written,direct,3280000.0000000,200000.0000000,3080000.0000000,1540.00;2024-01-01 00:00:00+00:00,not_written,direct,130000.0000000,250000.0000000,-120000.0000000,-48.00;2024-01-01 00:00:00+00:00,not_written,facultative-reinsurance,None,None,None,None;2024-02-01 00:00:00+00:00,not_written,direct,None,130000.0000000,None,None;2024-02-01 00:00:00+00:00,written,direct,87000.0000000,3280000.0000000,-3193000.0000000,-97.35;2024-03-01 00:00:00+00:00,not_written,direct,90000.0000000,None,None,None;2024-03-01 00:00:00+00:00,not_written,facultative-reinsurance,25000.0000000,None,None,None;2024-05-01 00:00:00+00:00,not_written,co-insurance,30000.0000000,None,None,None;2024-05-01 00:00:00+00:00,not_written,direct,915790.0000000,90000.0000000,825790.0000000,917.54;2024-05-01 00:00:00+00:00,written,facultative-reinsurance,150000.0000000,120000.0000000,30000.0000000,25.00;2024-06-01 00:00:00+00:00,not_written,direct,16615000.0000000,915790.0000000,15699210.0000000,1714.28;2024-06-01 00:00:00+00:00,written,direct,9180000.0000000,87000.0000000,9093000.0000000,10451.72;2024-06-01 00:00:00+00:00,not_written,facultative-reinsurance,None,25000.0000000,None,None;2024-07-01 00:00:00+00:00,not_written,direct,3115877.0000000,16615000.0000000,-13499123.0000000,-81.25;2024-07-01 00:00:00+00:00,written,direct,5150000.0000000,9180000.0000000,-4030000.0000000,-43.90;2024-08-01 00:00:00+00:00,not_written,direct,50000.0000000,3115877.0000000,-3065877.0000000,-98.40;2024-08-01 00:00:00+00:00,written,direct,605435000.0000000,5150000.0000000,600285000.0000000,11656.02;2024-09-01 00:00:00+00:00,not_written,co-insurance,None,30000.0000000,None,None;2024-09-01 00:00:00+00:00,written,direct,5475000.0000000,605435000.0000000,-599960000.0000000,-99.10;2024-09-01 00:00:00+00:00,not_written,direct,6400000.0000000,50000.0000000,6350000.0000000,12700.00;2024-09-01 00:00:00+00:00,not_written,facultative-reinsurance,None,None,None,None;2024-10-01 00:00:00+00:00,written,direct,900000.0000000,5475000.0000000,-4575000.0000000,-83.56;2024-10-01 00:00:00+00:00,not_written,direct,1490006.0000000,6400000.0000000,-4909994.0000000,-76.72;2024-10-01 00:00:00+00:00,not_written,facultative-reinsurance,None,None,None,None;2024-11-01 00:00:00+00:00,not_written,co-insurance,None,None,None,None;2024-11-01 00:00:00+00:00,written,direct,30525000.0000000,900000.0000000,29625000.0000000,3291.67;2024-11-01 00:00:00+00:00,not_written,direct,50001.0000000,1490006.0000000,-1440005.0000000,-96.64;2024-11-01 00:00:00+00:00,written,facultative-reinsurance,50000.0000000,150000.0000000,-100000.0000000,-66.67;2024-11-01 00:00:00+00:00,not_written,facultative-reinsurance,35000.0000000,None,None,None;2024-12-01 00:00:00+00:00,not_written,direct,620000.0000000,50001.0000000,569999.0000000,1139.98;2024-12-01 00:00:00+00:00,written,direct,84839182507.0000000,30525000.0000000,84808657507.0000000,277833.44;2024-12-01 00:00:00+00:00,not_written,facultative-reinsurance,None,35000.0000000,None,None;2025-01-01 00:00:00+00:00,not_written,direct,84274648353.0000000,620000.0000000,84274028353.0000000,13592585.22;2025-01-01 00:00:00+00:00,written,direct,2918791414.0000000,84839182507.0000000,-81920391093.0000000,-96.56;2025-01-01 00:00:00+00:00,not_written,facultative-reinsurance,None,None,None,None;2025-02-01 00:00:00+00:00,not_written,direct,60000.0000000,84274648353.0000000,-84274588353.0000000,-100.00;2025-02-01 00:00:00+00:00,not_written,facultative-reinsurance,None,None,None,None;2025-03-01 00:00:00+00:00,not_written,direct,315000.0000000,60000.0000000,255000.0000000,425.00;2025-03-01 00:00:00+00:00,written,direct,2200013.0000000,2918791414.0000000,-2916591401.0000000,-99.92;2025-04-01 00:00:00+00:00,not_written,co-insurance,None,None,None,None;2025-04-01 00:00:00+00:00,not_written,direct,220000.0000000,315000.0000000,-95000.0000000,-30.16;2025-05-01 00:00:00+00:00,written,direct,2000000.0000000,2200013.0000000,-200013.0000000,-9.09;2025-05-01 00:00:00+00:00,not_written,facultative-reinsurance,None,None,None,None;2025-05-01 00:00:00+00:00,written,facultative-reinsurance,50000.0000000,50000.0000000,0E-7,0.00;2025-06-01 00:00:00+00:00,written,direct,8000000.0000000,2000000.0000000,6000000.0000000,300.00;2025-06-01 00:00:00+00:00,not_written,direct,150000.0000000,220000.0000000,-70000.0000000,-31.82;2025-06-01 00:00:00+00:00,not_written,facultative-reinsurance,None,None,None,None;2025-06-01 00:00:00+00:00,written,facultative-reinsurance,50000.0000000,50000.0000000,0E-7,0.00;2025-07-01 00:00:00+00:00,written,direct,50000.0000000,8000000.0000000,-7950000.0000000,-99.38;2025-07-01 00:00:00+00:00,not_written,direct,120000.0000000,150000.0000000,-30000.0000000,-20.00']}
entry : {'question': 'Which is our premium share in comparison with the total bound GWP?', 'answer': 'Our premium share in comparison with the total bound GWP is 90.59%.', 'contexts': ['total premium (bound),total premium share (bound),premium share percentage 23600000.0000000,21378750.0000000000000000,90.587923728813559322000']}
entry : {'question': 'What has been the development of the GWP (our share) on the Novartis Property since 2024?', 'answer': 'There has been no recorded development of the GWP (your share) on the Novartis Property since 2024.', 'contexts': ['Query returned no results.']}
entry : {'question': 'What percentage of policies are above 1000?', 'answer': '39.18% of not written policies and 92.13% of written policies are above 1000.', 'contexts': ['total_policies,threshold,policies_above_threshold,policies_above_threshold_percentage,status_group 171,1000,67,39.18,not_written 89,1000,82,92.13,written']}
entry : {'question': 'How many policies are below 2000$ premium?', 'answer': 'There are 3 not written policies and 7 written policies below $2,000 premium.', 'contexts': ['total_policies,threshold,policies_below_threshold,status_group 171,2000,3,not_written 89,2000,7,written']}
entry : {'question': 'How many policies are above 1000$ premium?', 'answer': 'There are 67 not written policies and 82 written policies above $1,000 premium.', 'contexts': ['total_policies,threshold,policies_above_threshold,status_group 171,1000,67,not_written 89,1000,82,written']}
entry : {'question': 'How many policies are below 2000$ premium?', 'answer': 'There are 3 not written policies and 7 written policies below $2,000 premium.', 'contexts': ['total_policies,threshold,policies_below_threshold,status_group 171,2000,3,not_written 89,2000,7,written']}
entry : {'question': 'What are the top 5 regions/states contributing to premium revenue?', 'answer': 'The top 5 regions/states contributing to premium revenue are AT, ES, AF, BH, and GB.', 'contexts': [" status,risk_location,premium expired,['AT'],84839182506.0000000 expired,['ES'],2505450000.0000000 expired,['AF'],591600000.0000000 expired,['BH'],414141415.0000000 expired,['GB'],40115023.0000000"]}
entry : {'question': 'Can you show the split between the new business premium and the renewal premium?', 'answer': 'The renewal premium is $200,000, while the new business premium amount is not provided.', 'contexts': ['premium_type,premium_amount new business,None renewal,200000.0000000']}
entry : {'question': 'What is the premium retention rate for renewals?', 'answer': 'The premium retention rate for renewals is 0.0.', 'contexts': ['premium_type,premium_retention_rate renewal,0.0']}

#### 📝 Generate synthetic dataset using RAGAS | 🏗️ CBOT PROJECT

In [10]:
from langchain.schema import Document
from langchain_openai import AzureChatOpenAI, AzureOpenAIEmbeddings

# Convert real contexts to documents for RAGAS
docs = [Document(page_content=ctx) for entry in golden_real for ctx in entry["contexts"]]

# Split if necessary
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
split_documents = text_splitter.split_documents(docs)
print(f"Chunks generados para sintéticos: {len(split_documents)}")

# Initialize testset generator with Azure OpenAI
generator_llm = LangchainLLMWrapper(
    AzureChatOpenAI(
        azure_deployment=cfg.AZURE_OPENAI_LLM_DEPLOYMENT_NAME,
        openai_api_version=cfg.AZURE_OPENAI_API_VERSION,
        azure_endpoint=cfg.AZURE_OPENAI_API_ENDPOINT,
        api_key=cfg.AZURE_OPENAI_API_KEY,
        temperature=0
    )
)

generator_embeddings = LangchainEmbeddingsWrapper(
    AzureOpenAIEmbeddings(
        azure_deployment=cfg.AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME,
        openai_api_version=cfg.AZURE_OPENAI_API_VERSION,
        azure_endpoint=cfg.AZURE_OPENAI_API_ENDPOINT,
        api_key=cfg.AZURE_OPENAI_API_KEY
    )
)

generator = TestsetGenerator(llm=generator_llm, embedding_model=generator_embeddings)

# Generate synthetic dataset
dataset_synth = generator.generate_with_langchain_docs(split_documents, testset_size=10)
df_synth = pd.DataFrame(dataset_synth)
print(f"Synthetic Golden Dataset: {len(df_synth)} entries")

Chunks generados para sintéticos: 41

Applying SummaryExtractor:   0%|          | 0/19 [00:00<?, ?it/s]

Applying CustomNodeFilter:   0%|          | 0/41 [00:00<?, ?it/s]

Node 39ee260b-c60f-411e-8ca8-421b2fcb98e5 does not have a summary. Skipping filtering.
Node 02a98bfc-a1b7-40f3-a8c2-7c14fd8ece88 does not have a summary. Skipping filtering.
Node cf054490-57c5-489b-b718-afa4d8b3392c does not have a summary. Skipping filtering.
Node 366cf090-a225-47d6-a677-797d82c961b6 does not have a summary. Skipping filtering.
Node ec3c1cf5-87aa-45e9-8065-73d617bc0732 does not have a summary. Skipping filtering.
Node 3b93437d-6e5e-47d1-bb89-a1f3259aa4a8 does not have a summary. Skipping filtering.
Node d285531b-4bab-49ca-adda-1c5a88492549 does not have a summary. Skipping filtering.
Node 98506c6a-d5e7-4f21-8145-06fb2833c2fb does not have a summary. Skipping filtering.
Node 55eea9fc-7da4-4a70-b4d9-98e354fe6518 does not have a summary. Skipping filtering.
Node ead5aead-96de-413c-beed-dbc0890be1b6 does not have a summary. Skipping filtering.
Node 38414832-89a4-4d3c-aa71-22642b12105d does not have a summary. Skipping filtering.
Node 4619f127-d5cb-4a24-a673-9c59ac6b5da9 does not have a summary. Skipping filtering.
Node dc00a74f-4883-4d22-b418-a3f9737dc5d8 does not have a summary. Skipping filtering.
Node 236cc5e2-1f41-48e4-9e88-3e6007aefff7 does not have a summary. Skipping filtering.
Node 80337c3b-9258-482b-9210-4d2285f7d6a0 does not have a summary. Skipping filtering.
Node 52248d96-9e2d-4d40-a392-85c40c64c4b8 does not have a summary. Skipping filtering.
Node a31e0393-44d4-4861-9053-51c99b8ec1af does not have a summary. Skipping filtering.
Node fc4c95dc-6614-4b92-981b-ed048b415c41 does not have a summary. Skipping filtering.
Node 06511ba1-e6ba-40ec-8b06-82902794c008 does not have a summary. Skipping filtering.
Node af7a03fd-fd66-4d95-b19f-0d0df834be0c does not have a summary. Skipping filtering.
Node d2c229b1-010a-47d0-af39-47f96af5ffa9 does not have a summary. Skipping filtering.
Node 73c9b979-2331-4c2b-9d32-0a7e3f7c84f3 does not have a summary. Skipping filtering.

Applying [EmbeddingExtractor, ThemesExtractor, NERExtractor]:   0%|          | 0/101 [00:00<?, ?it/s]

Applying [CosineSimilarityBuilder, OverlapScoreBuilder]:   0%|          | 0/2 [00:00<?, ?it/s]

Generating personas:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/12 [00:00<?, ?it/s]

Synthetic Golden Dataset: 12 entries

#### 📝 Prepare and save synthetic dataset as EvaluationDataset | 🏗️ CBOT PROJECT

In [11]:
import pandas as pd
from ragas import EvaluationDataset

df = dataset_synth.to_pandas()
pd.set_option('display.max_colwidth', 200)
display(df)
df.to_csv("kitsune_demo_ragas_evaluations.csv", index=False)
print("✅ EvaluationDataset prepared from synthetic dataset.")

,user_input,reference_contexts,reference,synthesizer_name
0,"What is the status group and premium amount associated with the insurance policy reference DE2500169/R01, and how does it compare to the policy DE2400169 based on the provided transaction data?","[policy_reference,status_group,premium,row_num DE2500169/R01,not_written,84274527852.0000000,1 DE2400169,written,84274527852.0000000,1]","According to the provided transaction data, the insurance policy reference DE2500169/R01 has a status group of not_written and a premium amount of 84274527852.0000000. In comparison, the policy DE...",single_hop_specifc_query_synthesizer
1,What premium for DE2100126 policy?,"[policy_reference,premium DE2100126,1.0000000]",The premium for policy DE2100126 is 1.0000000.,single_hop_specifc_query_synthesizer
2,What DE2100098 mean?,"[policy_reference,premium_average,DE2100095,66.0000000000000000,DE2100098,1400000.000000000000,DE2100111,None,DE2100126,1.00000000000000000000,DE2100130,1.00000000000000000000,DE2100131,9.00000000...",DE2100098 have premium average 1400000.000000000000.,single_hop_specifc_query_synthesizer
3,What is the transaction amount for DE2300143?,"[00000000,DE2300138,30000.000000000000,DE2300139,15000.0000000000000000,DE2300140,10000.0000000000000000,DE2300141,60000.000000000000,DE2300142,50000.000000000000,DE2300143,10000.0000000000000000,...",The transaction amount for DE2300143 is 10000.0000000000000000.,single_hop_specifc_query_synthesizer
4,"Based on the available financial transactions and policy records, what patterns can be identified in the performance and completeness of facultative reinsurance policies, and how do missing or 'no...","[<1-hop>\n\n00000000,DE2300138,30000.000000000000,DE2300139,15000.0000000000000000,DE2300140,10000.0000000000000000,DE2300141,60000.000000000000,DE2300142,50000.000000000000,DE2300143,10000.000000...","Analysis of the provided financial transactions and policy records reveals several patterns regarding facultative reinsurance policies. In the <2-hop> segment, there are both 'written' and 'not_wr...",multi_hop_abstract_query_synthesizer
5,what insurance transactions got big financial transactions and written status?,"[<1-hop>\n\n00000000,DE2300138,30000.000000000000,DE2300139,15000.0000000000000000,DE2300140,10000.0000000000000000,DE2300141,60000.000000000000,DE2300142,50000.000000000000,DE2300143,10000.000000...","From the context, insurance transactions with written status and big financial transactions include: on 2024-12-01, a direct written transaction of 84839182507.0000000 with a previous value of 305...",multi_hop_abstract_query_synthesizer
6,"How you track policy status when some data missing and not written, and what problem with data completeness and integrity from these records in direct and facultative-reinsurance transactions?","[<1-hop>\n\n00:00:00+00:00,written,direct,39370000.0000000,50000.0000000,39320000.0000000,78640.00;2023-10-01 00:00:00+00:00,written,direct,200000.0000000,39370000.0000000,-39170000.0000000,-99.49...","Policy status tracking is hard when many records show not_written and missing values like None for amounts and dates, especially in direct and facultative-reinsurance transactions. For example, in...",multi_hop_abstract_query_synthesizer
7,"How much financial transactions and insurance transactions got None or not written, and what is the effect on total policy performance, like, if you look at the first context with all those DE num...","[<1-hop>\n\n5000.0000000000000000,DE2400043,50000.000000000000,DE2400044,None,DE2400046,50000.000000000000,DE2400047,2000000.000000000000,DE2400047/R01,589000000.00000000,DE2400048,455877.00000000...","In the first context, many financial transactions linked to DE numbers have None values, such as DE2400046, DE2400059, DE2400060, DE2400061, DE2400066, DE2400067, DE2400068, DE2400074, DE2400076, ...",multi_hop_abstract_query_synthesizer
8,"What are the recorded premium values for the policy references DE2100201 and DE2500162/R01, and how do their data completeness statuses compare across the provided insurance transaction records?","[<1-hop>\n\n94,2500.0000000000000000,DE2400224,None,DE2400226,None,DE2400227,None,DE2400249,None,DE2500093,100000.000000000000,DE2500134,None,DE2500161/R01,200000.000000000000,DE2500162/R01,1.0000...","According to the provided insurance transaction records, the policy reference DE2100201 appears in the <2-hop> segment with a premium value of None, indicating missing or incomplete data for this ...",multi_hop_specific_query_synthesizer
9,whts DE2400082 and DE2500208 amunt?,"[<1-hop>\n\n03,None,DE2500204,None,DE2500205,150000.000000000000,DE2500206,120000.000000000000,DE2500207,None,DE2500208,None,DE2500209,None,DE2500211,15000.0000000000000000,DE2500216,None,DE250021...","DE2400082 has an amount of 100000.000000000000 in <2-hop>, while DE2500208 has None in <1-hop>.",multi_hop_specific_query_synthesizer
10,"DE2400137 and DE2400227, what money they got?","[<1-hop>\n\n94,2500.0000000000000000,DE2400224,None,DE2400226,None,DE2400227,None,DE2400249,None,DE2500093,100000.000000000000,DE2500134,None,DE2500161/R01,200000.000000000000,DE2500162/R01,1.0000...",DE2400137 got 600000.000000000000 from <2-hop>. DE2400227 got None from both <1-hop> and <2-hop>.,multi_hop_specific_query_synthesizer
11,What are the written direct policy financial outcomes for 2024-09-01 and 2025-02-01?,"[<1-hop>\n\n00:00:00+00:00,written,direct,5150000.0000000,9180000.0000000,-4030000.0000000,-43.90;2024-08-01 00:00:00+00:00,not_written,direct,50000.0000000,3115877.0000000,-3065877.0000000,-98.40...","On 2024-09-01, the written direct policy had a premium of 5,475,000.0000000, a loss of 605,435,000.0000000, resulting in a net outcome of -599,960,000.0000000 and a loss ratio of -99.10. On 2025-0...",multi_hop_specific_query_synthesizer

✅ EvaluationDataset prepared from synthetic dataset.

#### 📝 Compile and initialize application graph | 🏗️ CBOT PROJECT

In [ ]:
from app.application.graph import compile_graph
from app.domain.domain import CbotState

graph = compile_graph()
print("✅ Grafo compilado correctamente")

✅ Grafo compilado correctamente

/home/xtallet/inari/inari-henzuru-data/app/application/graph.py:84: RuntimeWarning: coroutine 'compile_graph' was never awaited
  compile_graph()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

#### 📝 Execute compiled graph with sample question | 🏗️ CBOT PROJECT

In [ ]:
from app.application.graph import compile_graph
from app.domain.domain import CbotState

async def ejecutar_grafo(pregunta: str):
    graph = await compile_graph()
    
    initial_state = CbotState(
        question=pregunta,
        user_id="notebook_user",
        session_id=None
    )
    
    result = await graph.ainvoke(initial_state)
    return result

import asyncio
resultado = await ejecutar_grafo("How many policies do I have ?")
print(f"Response: {resultado}")

INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: SELECT COUNT(cp.policy_reference) AS total_policies FROM get_premiums() cp;
INFO:root:Running query: SELECT COUNT(cp.policy_reference) AS total_policies FROM get_premiums() cp;
INFO:root:Query result: total_policies
260
INFO:root:Querying Agno agent for summarization
INFO:root:User question: How many policies do I have ?
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: You have a total of 260 policies.

Respuesta: {'question': 'How many policies do I have ?', 'user_id': 'usuario_notebook', 'session_id': '042628a0-23ea-4128-b0ef-afa136480ce0', 'context': "question: Has the premium for policy RE2500547 changed over time? \ncot: Q: Has the premium for policy RE2500547 changed over time? A: We build a reference CTE named policy_reference that holds the policy reference user has asked about. Then, we select the policies from table _policies _policymodel related to this reference and displaying: id: policy_id, version: policy versioning id. 0 means original policy, 1 means first endorsement policy, etc, original_policy_without_endorsement_id: id of the original policy (the one that has version=0), previous_policy_of_endorsement_id: id of previous policy from which the endorsement has been created, inception_date: date where policy takes action, expiry_date: date when policy expires, status: current policy status, premium: policy amount. The SQL query is: WITH _policy_reference AS (SELECT 'RE2500021' AS reference) SELECT pm.id, pm.version, pm.original_policy_without_endorsement_id, pm.previous_policy_of_endorsement_id, pm.inception_date, pm.expiry_date, pm.status, total_gross_premium(pm.id) AS premium FROM _policy_reference _pr INNER JOIN policies_policymodel pm ON _pr.reference = pm.reference ORDER BY pm.version ASC;\nsql_query: WITH _policy_reference AS (SELECT 'RE2500021' AS reference) SELECT pm.id, pm.version, pm.original_policy_without_endorsement_id, pm.previous_policy_of_endorsement_id, pm.inception_date, pm.expiry_date, pm.status, total_gross_premium(pm.id) AS premium FROM _policy_reference _pr INNER JOIN policies_policymodel pm ON _pr.reference = pm.reference ORDER BY pm.version ASC;\n\nquestion: How many policies are below 2000$ premium?\ncot: CoT: Q: How many policies are below 2000$ premium? A: The primary data is provided through the custom PostgreSQL function 'get_premiums()'. This custom function internally calculates the premium of the policy and returns: policy_id : This is the policy identifier policy_reference: This is the reference of the policy is_endorsement : Boolean field which indicates if the policy is an endorsement or not status_group : which has 2 options 'written' and 'not_written' premium: the amount of the policy premium The query with a CTE _threshold that sets the premium threshold to be compared with. Then, select all the premiums from get_premiums() function to get all policies with a join to the _threshold CTE for making calculations. We perform a count on the policy_id, select the threshold to show it in the final answer and make two calculus: policies_below_threshold: integer that holds the number of policies with premium below the threshold Finally select the status_group field. The SQL query is: WITH _threshold AS (SELECT 2000 AS threshold) SELECT COUNT(cp.policy_reference) AS total_policies, th.threshold AS threshold, COUNT(CASE WHEN cp.premium < th.threshold THEN 1 END) AS policies_below_threshold, status_group FROM get_premiums() cp JOIN _threshold th ON TRUE GROUP BY th.threshold, status_group, th.threshold;\nsql_query: WITH _threshold AS (SELECT 2000 AS threshold) SELECT COUNT(cp.policy_reference) AS total_policies, th.threshold AS threshold, COUNT(CASE WHEN cp.premium < th.threshold THEN 1 END) AS policies_below_threshold, status_group FROM get_premiums() cp JOIN _threshold th ON TRUE GROUP BY th.threshold, status_group, th.threshold;\n\nquestion: How many policies are above 1000$ premium?\ncot: CoT: Q: How many policies are above 1000$ premium? A: The primary data is provided through the custom PostgreSQL function 'get_premiums()'. This custom function internally calculates the premium of the policy and returns: policy_id : This is the policy identifier policy_reference: This is the reference of the policy is_endorsement : Boolean field which indicates if the policy is an endorsement or not status_group : which has 2 options 'written' and 'not_written' premium: the amount of the policy premium The query with a CTE _threshold that sets the premium threshold to be compared with. Then, select all the premiums from get_premiums() function to get all policies with a join to the _threshold CTE for making calculations. We perform a count on the policy_id, select the threshold to show it in the final answer and make two calculus: policies_above_threshold: integer that holds the number of policies with premium above the threshold Finally select the status_group field. The SQL query is: WITH _threshold AS (SELECT 1000 AS threshold) SELECT COUNT(cp.policy_reference) AS total_policies, th.threshold AS threshold, COUNT(CASE WHEN cp.premium >= th.threshold THEN 1 END) AS policies_above_threshold, status_group FROM get_premiums() cp JOIN _threshold th ON TRUE GROUP BY th.threshold, status_group, th.threshold;\nsql_query: WITH _threshold AS (SELECT 1000 AS threshold) SELECT COUNT(cp.policy_reference) AS total_policies, th.threshold AS threshold, COUNT(CASE WHEN cp.premium >= th.threshold THEN 1 END) AS policies_above_threshold, status_group FROM get_premiums() cp JOIN _threshold th ON TRUE GROUP BY th.threshold, status_group, th.threshold;\n\nquestion: What is the premium for policy number RE2500547?\ncot: CoT: Q: What is the premium for policy number (reference) RE2500547? A: The primary data is provided through the custom PostgreSQL function 'get_premiums()'. This custom function internally calculates the premium of the policy and returns: policy_id : This is the policy identifier policy_reference: This is the reference of the policy is_endorsement : Boolean field which indicates if the policy is an endorsement or not status_group : which has 2 options 'written' and 'not_written' premium: the amount of the policy premium From 'get_premiums()' we filter the policy_reference by the reference the user provides. The SQL query is: SELECT cp.policy_reference, cp.premium FROM get_premiums() cp WHERE cp.policy_reference = 'RE2500547';\nsql_query: SELECT cp.policy_reference, cp.premium FROM get_premiums() cp WHERE cp.policy_reference = 'RE2500547';\n\nquestion: How many policies are below 2000$ premium?\ncot: CoT: Q: What percentage of policies are below 2000$ premium? A: The primary data is provided through the custom PostgreSQL function 'get_premiums()'. This custom function internally calculates the premium of the policy and returns: policy_id : This is the policy identifier policy_reference: This is the reference of the policy is_endorsement : Boolean field which indicates if the policy is an endorsement or not status_group : which has 2 options 'written' and 'not_written' premium: the amount of the policy premium The query with a CTE _threshold that sets the premium threshold to be compared with. Then, select all the premiums from get_premiums() function to get all policies with a join to the _threshold CTE for making calculations. We perform a count on the policy_id, select the threshold to show it in the final answer and make two calculus: policies_below_threshold: integer that holds the number of policies with premium below the threshold policies_below_threshold_percentage: numeric value that holds the percentage of the policies_below_threshold vs the total_policies. Finally select the status_group field. The SQL query is: WITH _threshold AS (SELECT 2000 AS threshold) SELECT COUNT(cp.policy_id) AS total_policies, th.threshold AS threshold, COUNT(CASE WHEN cp.premium < th.threshold THEN 1 END) AS policies_below_threshold, ROUND((COUNT(CASE WHEN cp.premium < th.threshold THEN 1 END) * 100.0 / COUNT(cp.policy_reference)), 2) AS policies_below_threshold_percentage, status_group FROM get_premiums() cp JOIN _threshold th ON TRUE WHERE cp.policy_id IS NOT NULL GROUP BY th.threshold, status_group;\nsql_query: WITH _threshold AS (SELECT 2000 AS threshold) SELECT COUNT(cp.policy_id) AS total_policies, th.threshold AS threshold, COUNT(CASE WHEN cp.premium < th.threshold THEN 1 END) AS policies_below_threshold, ROUND((COUNT(CASE WHEN cp.premium < th.threshold THEN 1 END) * 100.0 / COUNT(cp.policy_reference)), 2) AS policies_below_threshold_percentage, status_group FROM get_premiums() cp JOIN _threshold th ON TRUE WHERE cp.policy_id IS NOT NULL GROUP BY th.threshold, status_group;\n\nquestion: What is the premium retention rate for renewals?\ncot: CoT: Q: What is the premium retention rate for renewals? A: From table policies_policymodel we need to compute two values first: number of renewal policies: this is the count of renewed policies in bound status. Filters applied are transaction_type = 'renewal', status = 'bound' and version = 0. The policy version (named version) must be 0 to select the original policy always (if not, we could get this number by adding to this calculus the endorsed policies) number of total policies: this is the total number of bound policies. Also here is needed to filter by version = 0 Finally, we just compute the percentage between the number of renewal policies and the number of total policies. The query SQL is: SELECT 'renewal' AS premium_type, (SELECT COUNT(id) FROM policies_policymodel WHERE transaction_type = 'renewal' AND status = 'bound' AND version = 0) / (SELECT COUNT(id) FROM policies_policymodel WHERE status = 'bound' AND version = 0) * 100.0 AS premium_retention_rate;\nsql_query: SELECT 'renewal' AS premium_type, (SELECT COUNT(id) FROM policies_policymodel WHERE transaction_type = 'renewal' AND status = 'bound' AND version = 0) / (SELECT COUNT(id) FROM policies_policymodel WHERE status = 'bound' AND version = 0) * 100.0 AS premium_retention_rate;\n\nquestion: What percentage of policies are above [a certain premium threshold]?\ncot: CoT: Q: What percentage of policies are above 1000$ premium? A: The primary data is provided through the custom PostgreSQL function 'get_premiums()'. This custom function internally calculates the premium of the policy and returns: policy_id : This is the policy identifier policy_reference: This is the reference of the policy is_endorsement : Boolean field which indicates if the policy is an endorsement or not status_group : which has 2 options 'written' and 'not_written' premium: the amount of the policy premium The query with a CTE _threshold that sets the premium threshold to be compared with. Then, select all the premiums from get_premiums() function to get all policies with a join to the _threshold CTE for making calculations. We perform a count on the policy_id, select the threshold to show it in the final answer and make two calculus: policies_above_threshold: integer that holds the number of policies with premium above the threshold policies_above_threshold_percentage: numeric value that holds the percentage of the policies_above_threshold vs the total_policies. Finally select the status_group field. The SQL query is: WITH _threshold AS (SELECT 1000 AS threshold) SELECT COUNT(cp.policy_id) AS total_policies, th.threshold AS threshold, COUNT(CASE WHEN cp.premium >= th.threshold THEN 1 END) AS policies_above_threshold, ROUND((COUNT(CASE WHEN cp.premium >= th.threshold THEN 1 END) * 100.0 / COUNT(cp.policy_reference)), 2) AS policies_above_threshold_percentage, status_group FROM get_premiums() cp JOIN _threshold th ON TRUE WHERE cp.policy_id IS NOT NULL GROUP BY th.threshold, status_group;\nsql_query: WITH _threshold AS (SELECT 1000 AS threshold) SELECT COUNT(cp.policy_id) AS total_policies, th.threshold AS threshold, COUNT(CASE WHEN cp.premium >= th.threshold THEN 1 END) AS policies_above_threshold, ROUND((COUNT(CASE WHEN cp.premium >= th.threshold THEN 1 END) * 100.0 / COUNT(cp.policy_reference)), 2) AS policies_above_threshold_percentage, status_group FROM get_premiums() cp JOIN _threshold th ON TRUE WHERE cp.policy_id IS NOT NULL GROUP BY th.threshold, status_group;\n\nquestion: What are the top 5 regions/states contributing to premium revenue?\ncot: CoT: Q: What are the top 5 regions/states contributing to premium revenue? A: The primary data is provided through the custom PostgreSQL function 'get_premiums()'. This custom function internally calculates the premium of the policy and returns: policy_id : This is the policy identifier policy_reference: This is the reference of the policy is_endorsement : Boolean field which indicates if the policy is an endorsement or not status_group : which has 2 options 'written' and 'not_written' premium: the amount of the policy premium We select all the premiums from get_premiums() function to get all policies. Then, we perform several joins: policies_policymodel: to get more details of the policy, such as the policy status policies_locationmodel: to get the location details of the policy We select the grouped fields status and risk_location and the aggregated sum of the premium. Note that risk_location is the result of SQL COALESCE function between the countries_list and the states_list from table policies_locationmodel. It is this way because for US policies the countries_list will be NULL and the states_list a list of the insured US states. Query results are ordered by sum of the premium descendant and we limit to the first 5 results. The SQL query is: SELECT pm.status, COALESCE(plmm.countries_list, plmm.states_list) AS risk_location, sum(cp.premium) as premium FROM get_premiums() cp INNER JOIN policies_policymodel pm ON pm.id = cp.policy_id LEFT JOIN policies_locationmodel plmm ON pm.id = plmm.policy_id WHERE pm.status IN ('bound', 'expired') GROUP BY pm.status, COALESCE(plmm.countries_list, plmm.states_list) ORDER BY sum(cp.premium) DESC LIMIT 5;\nsql_query: SELECT pm.status, COALESCE(plmm.countries_list, plmm.states_list) AS risk_location, sum(cp.premium) as premium FROM get_premiums() cp INNER JOIN policies_policymodel pm ON pm.id = cp.policy_id LEFT JOIN policies_locationmodel plmm ON pm.id = plmm.policy_id WHERE pm.status IN ('bound', 'expired') GROUP BY pm.status, COALESCE(plmm.countries_list, plmm.states_list) ORDER BY sum(cp.premium) DESC LIMIT 5;", 'sql_query': 'SELECT COUNT(cp.policy_reference) AS total_policies FROM get_premiums() cp;', 'sql_result': 'total_policies\n260', 'answer': 'You have a total of 260 policies.'}

#### 📝 Run graph on synthetic dataset and collect responses | 🏗️ CBOT PROJECT

In [ ]:
from app.application.graph import compile_graph
import asyncio

graph = await compile_graph()

for test_row in dataset_synth:
    state = {
        "question": test_row.eval_sample.user_input,
        "user_id": "ragas-eval",
        "session_id": None,
    }
    result_state = await graph.ainvoke(state)

    # Agent response
    test_row.eval_sample.response = str(result_state.get("answer", "") or "")

    # Retrieved contexts (list[str] for RAGAS)
    ctx = result_state.get("context")
    if ctx is None:
        test_row.eval_sample.retrieved_contexts = []
    elif isinstance(ctx, list):
        test_row.eval_sample.retrieved_contexts = [str(c) for c in ctx]
    else:
        test_row.eval_sample.retrieved_contexts = [str(ctx)]

    await asyncio.sleep(6)

/tmp/ipykernel_39531/1799078718.py:4: RuntimeWarning: coroutine 'compile_graph' was never awaited
  graph = await compile_graph()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: SELECT policy_reference, status_group, premium FROM get_premiums() WHERE policy_reference IN ('DE2500169/R01', 'DE2400169');
INFO:root:Running query: SELECT policy_reference, status_group, premium FROM get_premiums() WHERE policy_reference IN ('DE2500169/R01', 'DE2400169');
INFO:root:Query result: policy_reference,status_group,premium
DE2400169,written,84274527852.0000000
DE2500169/R01,not_written,84274527852.0000000
INFO:root:Querying Agno agent for summarization
INFO:root:User question: What is the status group and premium amount associated with the insurance policy reference DE2500169/R01, and how does it compare to the policy DE2400169 based on the provided transaction data?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: The insurance policy DE2500169/R01 is in the "not_written" status group with a premium amount of 84,274,527,852.00, while DE2400169 is in the "written" status group with the same premium amount.
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: SELECT cp.policy_reference, cp.premium FROM get_premiums() cp WHERE cp.policy_reference = 'DE2100126';
INFO:root:Running query: SELECT cp.policy_reference, cp.premium FROM get_premiums() cp WHERE cp.policy_reference = 'DE2100126';
INFO:root:Query result: policy_reference,premium
DE2100126,1.0000000
INFO:root:Querying Agno agent for summarization
INFO:root:User question: What premium for DE2100126 policy?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: The premium for the DE2100126 policy is 1.0000000.
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: SELECT * FROM policies_policymodel WHERE reference = 'DE2100098';
INFO:root:Running query: SELECT * FROM policies_policymodel WHERE reference = 'DE2100098';
INFO:root:Query result: id,status,payment_terms_type,reference,inception_date,expiry_date,created,decline_reason,decline_comments,decline_author_name,ntu_reason,ntu_comments,ntu_author_name,insured_name,insured_country,insured_country_name,policy_type,sub_policy_type,coverage_type,policy_structure,transaction_type,period_of_insurance,capacity_written,capacity_bound,original_currency,roe,total_sum_insured_currency,total_sum_insured,total_sum_insured_prior_year_currency,total_sum_insured_prior_year,sum_insured_change_percentage,property_damage_currency,property_damage,property_damage_prior_year_currency,property_damage_prior_year,property_damage_change_percentage,business_interruption_currency,business_interruption,business_interruption_prior_year_currency,business_interruption_prior_year,business_interruption_change_percentage,indemnity_period,indemnity_period_prior_year,estimated_maximum_loss_currency,estimated_maximum_loss,premium_currency,premium,annualized_premium_currency,annualized_premium,premium_share_currency,premium_share,annualized_premium_share_currency,annualized_premium_share,premium_adjustable,ceding_deduction_percentage,brokerage_deduction_percentage,total_taxes_currency,total_taxes,total_net_premium_currency,total_net_premium,broker_id,author_id,brokerage_deduction_not_applicable,ceding_deduction_not_applicable,estimated_maximum_loss_share,estimated_maximum_loss_share_currency,premium_paid,premium_paid_date,bound_date,total_net_premium_share,total_net_premium_share_currency,total_taxes_share,total_taxes_share_currency,premium_base_rate_percentage,decline_date,ntu_date,original_policy_id,prebind_date,quote_date,additional_information,aggregate_total_limit,aggregate_total_limit_currency,aggregated_info_attachment,aggregated_info_attachment_currency,applicable_to_all_lob,attachment,business_interruption_current_year,business_interruption_current_year_currency,business_sector_id,ceding_commission_not_applicable,company_code,company_name,company_type,contact_person,description_of_operations,estimated_maximum_loss_eml_amount,estimated_maximum_loss_eml_amount_currency,estimated_maximum_loss_eml_share_amount,estimated_maximum_loss_eml_share_amount_currency,fully_earned_at_inception,indemnity_period_current_year,industry_sector_id,installment_taxes_split,lead_tracking,main_policy_type,mga_commission_not_applicable,mga_commission_percentage,number_of_employees_current_year,number_of_employees_prior_year,operating_incomes_current_year,operating_incomes_current_year_currency,operating_incomes_prior_year,operating_incomes_prior_year_currency,other_deduction_not_applicable,paid_by,property_damage_current_year,property_damage_current_year_currency,requested_deadline,rol,rpm,same_location_as_country_domicile,state,street_address,sub_status,submission_received,tax_not_applicable,total_sum_insured_current_year,total_sum_insured_current_year_currency,website_address,year_of_business_establishment,zipcode,cancellation_author,cancellation_date,cancellation_details,cancellation_other_details,cancellation_reason,is_premium_adjustable,additional_details,amount_insured,amount_insured_currency,entity_id,initial_premium,initial_premium_currency,insurable_interest,insurable_interest_other,insured_percentage,insured_transaction_amount,insured_transaction_amount_currency,loan_expiry_date,minimum_premium,minimum_premium_currency,minimum_retained_uninsured_percentage,obligor_business_sector_id,obligor_country_of_domicile,obligor_industry_sector_id,obligor_name,premium_rate,settlement_currency,team_id,umr,underwriter_id,aggregate_id,description,effective_date,endorsement_cancel_author_name,endorsement_cancel_comments,endorsement_cancel_date,endorsement_cancel_reason,endorsement_decline_reason,endorsement_reference,endorsement_type,internal_reference,is_endorsement,original_policy_without_endorsement_id,previous_policy_of_endorsement_id,version,additional_coverage_details,exclude_expiry_date,internal_expiry_date,origin,opened,expiration_locked,external_data,external_reference,external_data_sync_datetime,binding_broker_commission_not_applicable,binding_broker_commission_percentage,binding_authority_id,binding_authority_not_applicable,reporting_currency,request_for_approval_approved_date,request_for_approval_status,request_for_approval_skipped_rules,credit_control_last_sync_datetime,endorsement_created_after_policy_expiry,ceding_commission_percentage,section_label,retroactive_period_from,retroactive_period_to,draft_date,prequote_date,expired_date,triage_status,mark_as_viewed_in_triage
c721083c-457d-48fe-a442-ff1d34d148c6,prebind,single-payment,DE2100098,2021-07-01,2022-03-01,2024-10-09 09:28:57.224000+00:00,None,None,None,None,None,None,Qredo Ltd,GB,United Kingdom,direct,single,None,None,new,None,None,None,EUR,1.0000000,XYZ,None,XYZ,None,None,XYZ,None,XYZ,None,None,XYZ,None,XYZ,None,None,None,None,XYZ,None,XYZ,None,XYZ,None,XYZ,None,XYZ,None,None,None,None,XYZ,None,XYZ,None,5eef8d5e-8022-4e41-a566-d0eb6b5ece2d,9001,True,False,None,XYZ,False,None,None,None,XYZ,None,XYZ,None,None,None,None,2025-03-10,2025-03-10,None,None,XYZ,None,XYZ,True,['primary'],None,XYZ,5ac9cd10-08bf-4a7c-aa1b-a44eb5ed9a5f,True,01507274,Qredo Ltd,private,None,None,None,XYZ,None,XYZ,False,8,cceaa56c-e04f-4548-aa37-743f7b9a8b34,None,None,insurance,True,None,12,None,5000000.0000000,EUR,None,XYZ,True,broker,None,XYZ,None,None,None,True,None,None,set-premium,None,True,5000000.0000000,EUR,None,None,None,None,None,[],None,None,None,None,None,XYZ,None,None,XYZ,None,None,None,None,XYZ,None,None,XYZ,None,None,None,None,None,None,EUR,None,None,None,c721083c-457d-48fe-a442-ff1d34d148c6,None,None,None,None,None,None,None,None,[],None,False,None,None,0,None,False,2022-03-01,submission-intake,True,False,None,None,None,True,None,None,True,USD,None,None,[],None,False,None,None,None,2021-07-01,None,None,None,None,False
INFO:root:Querying Agno agent for summarization
INFO:root:User question: What DE2100098 mean?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: DE2100098 is the reference number for a direct, single-payment insurance policy for Qredo Ltd in the United Kingdom, with an inception date of July 1, 2021, and expiry date of March 1, 2022.
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: SELECT transaction_amount FROM transactions_transactionmodel WHERE transaction_reference = 'DE2300143';
INFO:root:Running query: SELECT transaction_amount FROM transactions_transactionmodel WHERE transaction_reference = 'DE2300143';

ERROR    Database error: relation "transactions_transactionmodel" does not exist
         LINE 1: SELECT transaction_amount FROM transactions_transactionmodel...
                                                ^

INFO:root:Query result: Error executing query: relation "transactions_transactionmodel" does not exist
LINE 1: SELECT transaction_amount FROM transactions_transactionmodel...
                                       ^
INFO:root:Querying Agno agent for summarization
INFO:root:User question: What is the transaction amount for DE2300143?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: I don't have the information to answer that question.
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: WITH facultative_policies AS (
    SELECT
        gp.policy_reference,
        gp.status_group,
        gp.premium,
        pm.status,
        pm.completeness,
        pm.bound_date
    FROM get_premiums() gp
    LEFT JOIN policies_policymodel pm ON gp.policy_id = pm.id
    WHERE pm.policy_type = 'facultative'
)
SELECT
    status_group,
    completeness,
    COUNT(*) AS policy_count,
    SUM(premium) AS total_premium,
    AVG(premium) AS avg_premium
FROM facultative_policies
GROUP BY status_group, completeness
ORDER BY status_group, completeness;

-- Impact analysis of missing or 'not_written' entries vs written
SELECT
    status_group,
    SUM(premium) AS total_premium,
    COUNT(*) AS policy_count
FROM facultative_policies
GROUP BY status_group
ORDER BY status_group;
INFO:root:Running query: WITH facultative_policies AS (
    SELECT
        gp.policy_reference,
        gp.status_group,
        gp.premium,
        pm.status,
        pm.completeness,
        pm.bound_date
    FROM get_premiums() gp
    LEFT JOIN policies_policymodel pm ON gp.policy_id = pm.id
    WHERE pm.policy_type = 'facultative'
)
SELECT
    status_group,
    completeness,
    COUNT(*) AS policy_count,
    SUM(premium) AS total_premium,
    AVG(premium) AS avg_premium
FROM facultative_policies
GROUP BY status_group, completeness
ORDER BY status_group, completeness;

-- Impact analysis of missing or 'not_written' entries vs written
SELECT
    status_group,
    SUM(premium) AS total_premium,
    COUNT(*) AS policy_count
FROM facultative_policies
GROUP BY status_group
ORDER BY status_group;

ERROR    Database error: column pm.completeness does not exist
         LINE 7:         pm.completeness,
                         ^

INFO:root:Query result: Error executing query: column pm.completeness does not exist
LINE 7:         pm.completeness,
                ^
INFO:root:Querying Agno agent for summarization
INFO:root:User question: Based on the available financial transactions and policy records, what patterns can be identified in the performance and completeness of facultative reinsurance policies, and how do missing or 'not_written' entries impact the overall financial outcomes compared to written facultative reinsurance transactions?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: I don't have the information to answer that question.
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: SELECT cp.policy_reference, cp.premium, cp.status_group
FROM get_premiums() cp
WHERE cp.premium >= 100000 AND cp.status_group = 'written'
ORDER BY cp.premium DESC;
INFO:root:Running query: SELECT cp.policy_reference, cp.premium, cp.status_group
FROM get_premiums() cp
WHERE cp.premium >= 100000 AND cp.status_group = 'written'
ORDER BY cp.premium DESC;
INFO:root:Query result: policy_reference,premium,status_group
DE2400169,84274527852.0000000,written
DE2500169,2500000000.0000000,written
DE2400047/R01,589000000.0000000,written
DE2400159,564654654.0000000,written
DE2500170,414141414.0000000,written
DE2400131,30000000.0000000,written
DE2400057,15000000.0000000,written
DE2300146,10000000.0000000,written
DE2300122,10000000.0000000,written
DE2300234,10000000.0000000,written
DE2500250,8000000.0000000,written
DE2300120,5050000.0000000,written
DE2400052,5000000.0000000,written
S.2400026,4400000.0000000,written
DE2500171,4100000.0000000,written
DE2400085,3000000.0000000,written
S.2400029,2000000.0000000,written
DE2300235,2000000.0000000,written
DE2400075,2000000.0000000,written
DE2500246,2000000.0000000,written
DE2400038,2000000.0000000,written
DE2500198,1500000.0000000,written
DE2300215,1200000.0000000,written
DE2400102,1100000.0000000,written
DE2400058,1000000.0000000,written
DE2400107,1000000.0000000,written
DE2400077,1000000.0000000,written
DE2500199,700000.0000000,written
DE2100221,600000.0000000,written
DE2400039,600000.0000000,written
DE2400145,525000.0000000,written
DE2400079,500000.0000000,written
DE2300147,200000.0000000,written
DE2300214,200000.0000000,written
DE2300124,200000.0000000,written
DE2300132,200000.0000000,written
DE2400106,200000.0000000,written
DE2300071,200000.0000000,written
DE2400071/R01,200000.0000000,written
DE2400065,150000.0000000,written
S.2400019,150000.0000000,written
DE2400062,150000.0000000,written
DE2400193,150000.0000000,written
DE2500228,150000.0000000,written
DE2500181,130000.0000000,written
DE2500247,120000.0000000,written
S.2300008,120000.0000000,written
DE2400084,100000.0000000,written
DE2400082,100000.0000000,written
DE2500093,100000.0000000,written
DE2400083,100000.0000000,written
DE2400063,100000.0000000,written
DE2400064,100000.0000000,written
INFO:root:Querying Agno agent for summarization
INFO:root:User question: what insurance transactions got big financial transactions and written status?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: The insurance transactions with big financial transactions and written status include policies like DE2400169 with a premium of 84,274,527,852; DE2500169 with 2,500,000,000; DE2400047/R01 with 589,000,000; and several others with premiums ranging from millions downwards, all marked as "written."
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: SELECT
  pm.id AS policy_id,
  pm.reference AS policy_reference,
  pm.status,
  CASE
    WHEN pm.status IN ('bound', 'expired', 'declined', 'not-taken-up', 'cancelled') THEN 'direct'
    WHEN pm.status IN ('facultative-bound', 'facultative-expired', 'facultative-declined', 'facultative-not-taken-up', 'facultative-cancelled') THEN 'facultative-reinsurance'
    ELSE 'unknown'
  END AS transaction_type,
  CASE
    WHEN pm.status_group IS NULL OR pm.status IS NULL OR gp.premium IS NULL THEN 'incomplete'
    ELSE 'complete'
  END AS data_completeness,
  gp.status_group,
  gp.premium,
  CASE
    WHEN pm.status_group IS NULL OR pm.status IS NULL OR gp.premium IS NULL THEN 'Missing critical data: status_group, status, or premium. Data integrity compromised; policy status cannot be reliably tracked.'
    ELSE 'Data sufficient for policy status tracking.'
  END AS integrity_issue
FROM get_premiums() gp
LEFT JOIN policies_policymodel pm ON gp.policy_id = pm.id
WHERE pm.status IN (
  'bound', 'expired', 'declined', 'not-taken-up', 'cancelled',
  'facultative-bound', 'facultative-expired', 'facultative-declined', 'facultative-not-taken-up', 'facultative-cancelled'
)
ORDER BY data_completeness, transaction_type, pm.status;
INFO:root:Running query: SELECT
  pm.id AS policy_id,
  pm.reference AS policy_reference,
  pm.status,
  CASE
    WHEN pm.status IN ('bound', 'expired', 'declined', 'not-taken-up', 'cancelled') THEN 'direct'
    WHEN pm.status IN ('facultative-bound', 'facultative-expired', 'facultative-declined', 'facultative-not-taken-up', 'facultative-cancelled') THEN 'facultative-reinsurance'
    ELSE 'unknown'
  END AS transaction_type,
  CASE
    WHEN pm.status_group IS NULL OR pm.status IS NULL OR gp.premium IS NULL THEN 'incomplete'
    ELSE 'complete'
  END AS data_completeness,
  gp.status_group,
  gp.premium,
  CASE
    WHEN pm.status_group IS NULL OR pm.status IS NULL OR gp.premium IS NULL THEN 'Missing critical data: status_group, status, or premium. Data integrity compromised; policy status cannot be reliably tracked.'
    ELSE 'Data sufficient for policy status tracking.'
  END AS integrity_issue
FROM get_premiums() gp
LEFT JOIN policies_policymodel pm ON gp.policy_id = pm.id
WHERE pm.status IN (
  'bound', 'expired', 'declined', 'not-taken-up', 'cancelled',
  'facultative-bound', 'facultative-expired', 'facultative-declined', 'facultative-not-taken-up', 'facultative-cancelled'
)
ORDER BY data_completeness, transaction_type, pm.status;

ERROR    Database error: column pm.status_group does not exist
         LINE 11:     WHEN pm.status_group IS NULL OR pm.status IS NULL OR gp....
                           ^
         HINT:  Perhaps you meant to reference the column "gp.status_group".

INFO:root:Query result: Error executing query: column pm.status_group does not exist
LINE 11:     WHEN pm.status_group IS NULL OR pm.status IS NULL OR gp....
                  ^
HINT:  Perhaps you meant to reference the column "gp.status_group".
INFO:root:Querying Agno agent for summarization
INFO:root:User question: How you track policy status when some data missing and not written, and what problem with data completeness and integrity from these records in direct and facultative-reinsurance transactions?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: The problem is that missing or incorrectly referenced columns (like pm.status_group) can prevent accurate tracking of policy status, leading to data completeness and integrity issues in direct and facultative-reinsurance transactions.
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: SELECT
    COUNT(*) FILTER (WHERE gp.premium IS NULL) AS financial_transactions_none,
    COUNT(*) FILTER (WHERE pm.status_group IN ('None', 'not_written')) AS insurance_transactions_none_or_not_written,
    SUM(gp.premium) FILTER (WHERE gp.premium IS NULL OR pm.status_group IN ('None', 'not_written')) AS total_premium_with_data_gaps,
    SUM(gp.premium) AS total_premium,
    ROUND(
        (SUM(gp.premium) FILTER (WHERE gp.premium IS NULL OR pm.status_group IN ('None', 'not_written')) * 100.0) / NULLIF(SUM(gp.premium), 0),
        2
    ) AS percent_premium_affected_by_data_gaps
FROM get_premiums() gp
LEFT JOIN policies_policymodel pm ON gp.policy_id = pm.id;
INFO:root:Running query: SELECT
    COUNT(*) FILTER (WHERE gp.premium IS NULL) AS financial_transactions_none,
    COUNT(*) FILTER (WHERE pm.status_group IN ('None', 'not_written')) AS insurance_transactions_none_or_not_written,
    SUM(gp.premium) FILTER (WHERE gp.premium IS NULL OR pm.status_group IN ('None', 'not_written')) AS total_premium_with_data_gaps,
    SUM(gp.premium) AS total_premium,
    ROUND(
        (SUM(gp.premium) FILTER (WHERE gp.premium IS NULL OR pm.status_group IN ('None', 'not_written')) * 100.0) / NULLIF(SUM(gp.premium), 0),
        2
    ) AS percent_premium_affected_by_data_gaps
FROM get_premiums() gp
LEFT JOIN policies_policymodel pm ON gp.policy_id = pm.id;

ERROR    Database error: column pm.status_group does not exist
         LINE 3:     COUNT(*) FILTER (WHERE pm.status_group IN ('None', 'not_...
                                            ^
         HINT:  Perhaps you meant to reference the column "gp.status_group".

INFO:root:Query result: Error executing query: column pm.status_group does not exist
LINE 3:     COUNT(*) FILTER (WHERE pm.status_group IN ('None', 'not_...
                                   ^
HINT:  Perhaps you meant to reference the column "gp.status_group".
INFO:root:Querying Agno agent for summarization
INFO:root:User question: How much financial transactions and insurance transactions got None or not written, and what is the effect on total policy performance, like, if you look at the first context with all those DE numbers and None values, and then in the second context, you see not_written and None for some insurance transactions, so what does it mean for the financial outcomes and data gaps, and how does it make it hard for analyst to decide about the policies?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: I don't have the information to answer that question.
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: SELECT cp.policy_reference, cp.premium, cp.status_group, it.data_completeness_status
FROM get_premiums() cp
LEFT JOIN insurance_transactions it ON cp.policy_reference = it.policy_reference
WHERE cp.policy_reference IN ('DE2100201', 'DE2500162/R01');
INFO:root:Running query: SELECT cp.policy_reference, cp.premium, cp.status_group, it.data_completeness_status
FROM get_premiums() cp
LEFT JOIN insurance_transactions it ON cp.policy_reference = it.policy_reference
WHERE cp.policy_reference IN ('DE2100201', 'DE2500162/R01');

ERROR    Database error: relation "insurance_transactions" does not exist
         LINE 3: LEFT JOIN insurance_transactions it ON cp.policy_reference =...
                           ^

INFO:root:Query result: Error executing query: relation "insurance_transactions" does not exist
LINE 3: LEFT JOIN insurance_transactions it ON cp.policy_reference =...
                  ^
INFO:root:Querying Agno agent for summarization
INFO:root:User question: What are the recorded premium values for the policy references DE2100201 and DE2500162/R01, and how do their data completeness statuses compare across the provided insurance transaction records?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: I don't have the information to answer that question.
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: SELECT cp.policy_reference, cp.premium FROM get_premiums() cp WHERE cp.policy_reference IN ('DE2400082', 'DE2500208');
INFO:root:Running query: SELECT cp.policy_reference, cp.premium FROM get_premiums() cp WHERE cp.policy_reference IN ('DE2400082', 'DE2500208');
INFO:root:Query result: policy_reference,premium
DE2400082,100000.0000000
DE2500208,None
INFO:root:Querying Agno agent for summarization
INFO:root:User question: whts DE2400082 and DE2500208 amunt?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: The amount for DE2400082 is 100,000, and there is no amount provided for DE2500208.
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: SELECT cp.policy_reference, cp.premium FROM get_premiums() cp WHERE cp.policy_reference IN ('DE2400137', 'DE2400227');
INFO:root:Running query: SELECT cp.policy_reference, cp.premium FROM get_premiums() cp WHERE cp.policy_reference IN ('DE2400137', 'DE2400227');
INFO:root:Query result: policy_reference,premium
DE2400137,600000.0000000
DE2400227,None
INFO:root:Querying Agno agent for summarization
INFO:root:User question: DE2400137 and DE2400227, what money they got?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: DE2400137 received 600,000, while DE2400227 did not receive any money.
INFO:root:Successfully connected to LanceDB and opened table: synthetic_data
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-embedding/embeddings?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:root:Generated SQL query: WITH written_policies AS (
    SELECT gp.policy_reference, pm.bound_date, pm.insured_name,
        (SELECT SUM((plm.total_layer_premium::NUMERIC * plm.share) / 100.0)
         FROM policies_policymodel pm2
         LEFT JOIN policies_limitmodel plm ON pm2.id = plm.policy_id
         WHERE pm2.reference = gp.policy_reference AND pm2.id = gp.policy_id) AS premium_share,
        (SELECT STRING_AGG(elob.name, ', ')
         FROM policies_policymodel pm2
         LEFT JOIN policies_limitmodel plm ON pm2.id = plm.policy_id
         LEFT JOIN policies_limitmodel_lines_of_business plob ON plm.id = plob.limitmodel_id
         LEFT JOIN entities_lineofbusinessmodel elob ON plob.lineofbusinessmodel_id = elob.id
         WHERE pm2.reference = gp.policy_reference AND pm2.id = gp.policy_id) AS line_of_business
    FROM get_premiums() gp
    LEFT JOIN policies_policymodel pm ON gp.policy_id = pm.id
    WHERE pm.status = 'bound' AND gp.status_group = 'written'
)
SELECT bound_date, premium_share, insured_name, line_of_business
FROM written_policies
WHERE bound_date IN ('2024-09-01', '2025-02-01')
ORDER BY bound_date ASC;
INFO:root:Running query: WITH written_policies AS (
    SELECT gp.policy_reference, pm.bound_date, pm.insured_name,
        (SELECT SUM((plm.total_layer_premium::NUMERIC * plm.share) / 100.0)
         FROM policies_policymodel pm2
         LEFT JOIN policies_limitmodel plm ON pm2.id = plm.policy_id
         WHERE pm2.reference = gp.policy_reference AND pm2.id = gp.policy_id) AS premium_share,
        (SELECT STRING_AGG(elob.name, ', ')
         FROM policies_policymodel pm2
         LEFT JOIN policies_limitmodel plm ON pm2.id = plm.policy_id
         LEFT JOIN policies_limitmodel_lines_of_business plob ON plm.id = plob.limitmodel_id
         LEFT JOIN entities_lineofbusinessmodel elob ON plob.lineofbusinessmodel_id = elob.id
         WHERE pm2.reference = gp.policy_reference AND pm2.id = gp.policy_id) AS line_of_business
    FROM get_premiums() gp
    LEFT JOIN policies_policymodel pm ON gp.policy_id = pm.id
    WHERE pm.status = 'bound' AND gp.status_group = 'written'
)
SELECT bound_date, premium_share, insured_name, line_of_business
FROM written_policies
WHERE bound_date IN ('2024-09-01', '2025-02-01')
ORDER BY bound_date ASC;
INFO:root:Query result: Query returned no results.
Columns: bound_date, premium_share, insured_name, line_of_business
INFO:root:Querying Agno agent for summarization
INFO:root:User question: What are the written direct policy financial outcomes for 2024-09-01 and 2025-02-01?
WARNING:opentelemetry.trace:Overriding of current TracerProvider is not allowed
WARNING:opentelemetry.instrumentation.instrumentor:Attempting to instrument while already instrumented
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-10-21 "HTTP/1.1 200 OK"

WARNING  MemoryDb not provided.

INFO:httpx:HTTP Request: POST https://api.agno.com/v1/telemetry/agent/run/create "HTTP/1.1 200 OK"
INFO:root:Generated summary from Agno: There are no written direct policy financial outcomes for 2024-09-01 and 2025-02-01.

#### 📝 Convert synthetic dataset to DataFrame and save with new columns | 🏗️ CBOT PROJECT

In [15]:
import pandas as pd
from ragas import EvaluationDataset

df = dataset_synth.to_pandas()
pd.set_option('display.max_colwidth', 200)
display(df)
df.to_csv("kitsune_demo_ragas_evaluations_new_cols.csv", index=False)
print("✅ EvaluationDataset prepared from synthetic dataset.")

,user_input,retrieved_contexts,reference_contexts,response,reference,synthesizer_name
0,"What is the status group and premium amount associated with the insurance policy reference DE2500169/R01, and how does it compare to the policy DE2400169 based on the provided transaction data?",[question: What is the premium for policy number RE2500547?\ncot: CoT: Q: What is the premium for policy number (reference) RE2500547? A: The primary data is provided through the custom PostgreSQL...,"[policy_reference,status_group,premium,row_num DE2500169/R01,not_written,84274527852.0000000,1 DE2400169,written,84274527852.0000000,1]","The insurance policy DE2500169/R01 is in the ""not_written"" status group with a premium amount of 84,274,527,852.00, while DE2400169 is in the ""written"" status group with the same premium amount.","According to the provided transaction data, the insurance policy reference DE2500169/R01 has a status group of not_written and a premium amount of 84274527852.0000000. In comparison, the policy DE...",single_hop_specifc_query_synthesizer
1,What premium for DE2100126 policy?,[question: What is the premium for policy number RE2500547?\ncot: CoT: Q: What is the premium for policy number (reference) RE2500547? A: The primary data is provided through the custom PostgreSQL...,"[policy_reference,premium DE2100126,1.0000000]",The premium for the DE2100126 policy is 1.0000000.,The premium for policy DE2100126 is 1.0000000.,single_hop_specifc_query_synthesizer
2,What DE2100098 mean?,[question: What is the premium for policy number RE2500547?\ncot: CoT: Q: What is the premium for policy number (reference) RE2500547? A: The primary data is provided through the custom PostgreSQL...,"[policy_reference,premium_average,DE2100095,66.0000000000000000,DE2100098,1400000.000000000000,DE2100111,None,DE2100126,1.00000000000000000000,DE2100130,1.00000000000000000000,DE2100131,9.00000000...","DE2100098 is the reference number for a direct, single-payment insurance policy for Qredo Ltd in the United Kingdom, with an inception date of July 1, 2021, and expiry date of March 1, 2022.",DE2100098 have premium average 1400000.000000000000.,single_hop_specifc_query_synthesizer
3,What is the transaction amount for DE2300143?,[question: What is the premium for policy number RE2500547?\ncot: CoT: Q: What is the premium for policy number (reference) RE2500547? A: The primary data is provided through the custom PostgreSQL...,"[00000000,DE2300138,30000.000000000000,DE2300139,15000.0000000000000000,DE2300140,10000.0000000000000000,DE2300141,60000.000000000000,DE2300142,50000.000000000000,DE2300143,10000.0000000000000000,...",I don't have the information to answer that question.,The transaction amount for DE2300143 is 10000.0000000000000000.,single_hop_specifc_query_synthesizer
4,"Based on the available financial transactions and policy records, what patterns can be identified in the performance and completeness of facultative reinsurance policies, and how do missing or 'no...",[question: What is the premium retention rate for renewals?\ncot: CoT: Q: What is the premium retention rate for renewals? A: From table policies_policymodel we need to compute two values first: n...,"[<1-hop>\n\n00000000,DE2300138,30000.000000000000,DE2300139,15000.0000000000000000,DE2300140,10000.0000000000000000,DE2300141,60000.000000000000,DE2300142,50000.000000000000,DE2300143,10000.000000...",I don't have the information to answer that question.,"Analysis of the provided financial transactions and policy records reveals several patterns regarding facultative reinsurance policies. In the <2-hop> segment, there are both 'written' and 'not_wr...",multi_hop_abstract_query_synthesizer
5,what insurance transactions got big financial transactions and written status?,[question: Can you show the split between the new business premium and the renewal premium?\ncot: CoT: Q: Can you show the split between the new business premium and the renewal premium? A: The pr...,"[<1-hop>\n\n00000000,DE2300138,30000.000000000000,DE2300139,15000.0000000000000000,DE2300140,10000.0000000000000000,DE2300141,60000.000000000000,DE2300142,50000.000000000000,DE2300143,10000.000000...","The insurance transactions with big financial transactions and written status include policies like DE2400169 with a premium of 84,274,527,852; DE2500169 with 2,500,000,000; DE2400047/R01 with 589...","From the context, insurance transactions with written status and big financial transactions include: on 2024-12-01, a direct written transaction of 84839182507.0000000 with a previous value of 305...",multi_hop_abstract_query_synthesizer
6,"How you track policy status when some data missing and not written, and what problem with data completeness and integrity from these records in direct and facultative-reinsurance transactions?",[question: What are the top 5 regions/states contributing to premium revenue?\ncot: CoT: Q: What are the top 5 regions/states contributing to premium revenue? A: The primary data is provided throu...,"[<1-hop>\n\n00:00:00+00:00,written,direct,39370000.0000000,50000.0000000,39320000.0000000,78640.00;2023-10-01 00:00:00+00:00,written,direct,200000.0000000,39370000.0000000,-39170000.0000000,-99.49...","The problem is that missing or incorrectly referenced columns (like pm.status_group) can prevent accurate tracking of policy status, leading to data completeness and integrity issues in direct and...","Policy status tracking is hard when many records show not_written and missing values like None for amounts and dates, especially in direct and facultative-reinsurance transactions. For example, in...",multi_hop_abstract_query_synthesizer
7,"How much financial transactions and insurance transactions got None or not written, and what is the effect on total policy performance, like, if you look at the first context with all those DE num...",[question: What is the premium retention rate for renewals?\ncot: CoT: Q: What is the premium retention rate for renewals? A: From table policies_policymodel we need to compute two values first: n...,"[<1-hop>\n\n5000.0000000000000000,DE2400043,50000.000000000000,DE2400044,None,DE2400046,50000.000000000000,DE2400047,2000000.000000000000,DE2400047/R01,589000000.00000000,DE2400048,455877.00000000...",I don't have the information to answer that question.,"In the first context, many financial transactions linked to DE numbers have None values, such as DE2400046, DE2400059, DE2400060, DE2400061, DE2400066, DE2400067, DE2400068, DE2400074, DE2400076, ...",multi_hop_abstract_query_synthesizer
8,"What are the recorded premium values for the policy references DE2100201 and DE2500162/R01, and how do their data completeness statuses compare across the provided insurance transaction records?",[question: What is the premium for policy number RE2500547?\ncot: CoT: Q: What is the premium for policy number (reference) RE2500547? A: The primary data is provided through the custom PostgreSQL...,"[<1-hop>\n\n94,2500.0000000000000000,DE2400224,None,DE2400226,None,DE2400227,None,DE2400249,None,DE2500093,100000.000000000000,DE2500134,None,DE2500161/R01,200000.000000000000,DE2500162/R01,1.0000...",I don't have the information to answer that question.,"According to the provided insurance transaction records, the policy reference DE2100201 appears in the <2-hop> segment with a premium value of None, indicating missing or incomplete data for this ...",multi_hop_specific_query_synthesizer
9,whts DE2400082 and DE2500208 amunt?,[question: What is the premium for policy number RE2500547?\ncot: CoT: Q: What is the premium for policy number (reference) RE2500547? A: The primary data is provided through the custom PostgreSQL...,"[<1-hop>\n\n03,None,DE2500204,None,DE2500205,150000.000000000000,DE2500206,120000.000000000000,DE2500207,None,DE2500208,None,DE2500209,None,DE2500211,15000.0000000000000000,DE2500216,None,DE250021...","The amount for DE2400082 is 100,000, and there is no amount provided for DE2500208.","DE2400082 has an amount of 100000.000000000000 in <2-hop>, while DE2500208 has None in <1-hop>.",multi_hop_specific_query_synthesizer
10,"DE2400137 and DE2400227, what money they got?",[question: What is the premium for policy number RE2500547?\ncot: CoT: Q: What is the premium for policy number (reference) RE2500547? A: The primary data is provided through the custom PostgreSQL...,"[<1-hop>\n\n94,2500.0000000000000000,DE2400224,None,DE2400226,None,DE2400227,None,DE2400249,None,DE2500093,100000.000000000000,DE2500134,None,DE2500161/R01,200000.000000000000,DE2500162/R01,1.0000...","DE2400137 received 600,000, while DE2400227 did not receive any money.",DE2400137 got 600000.000000000000 from <2-hop>. DE2400227 got None from both <1-hop> and <2-hop>.,multi_hop_specific_query_synthesizer
11,What are the written direct policy financial outcomes for 2024-09-01 and 2025-02-01?,[question: What has been the development of the GWP (our share) on the [Insured name] [Line of business] since [year]?\ncot: CoT: Q: What has been the development of the GWP (our share) on the [In...,"[<1-hop>\n\n00:00:00+00:00,written,direct,5150000.0000000,9180000.0000000,-4030000.0000000,-43.90;2024-08-01 00:00:00+00:00,not_written,direct,50000.0000000,3115877.0000000,-3065877.0000000,-98.40...",There are no written direct policy financial outcomes for 2024-09-01 and 2025-02-01.,"On 2024-09-01, the written direct policy had a premium of 5,475,000.0000000, a loss of 605,435,000.0000000, resulting in a net outcome of -599,960,000.0000000 and a loss ratio of -99.10. On 2025-0...",multi_hop_specific_query_synthesizer

✅ EvaluationDataset prepared from synthetic dataset.

In [16]:
from ragas import EvaluationDataset, evaluate, RunConfig
from ragas.metrics import (
    LLMContextRecall,
    FactualCorrectness,
    ContextEntityRecall,
    NoiseSensitivity
)
from ragas.llms import LangchainLLMWrapper
from langchain_openai import ChatOpenAI
import time

#### 📝 Evaluate synthetic dataset with custom metrics using RAGAS | 🏗️ CBOT PROJECT

In [17]:
from ragas.llms import LangchainLLMWrapper
from langchain_openai import AzureChatOpenAI
from ragas import evaluate, RunConfig, EvaluationDataset
from ragas.metrics import LLMContextRecall, FactualCorrectness, ContextEntityRecall, NoiseSensitivity

# Configurar el LLM de Azure OpenAI para evaluación
evaluator_llm = LangchainLLMWrapper(
    AzureChatOpenAI(
        azure_deployment=cfg.AZURE_OPENAI_LLM_DEPLOYMENT_NAME,
        openai_api_version=cfg.AZURE_OPENAI_API_VERSION,
        azure_endpoint=cfg.AZURE_OPENAI_API_ENDPOINT,
        api_key=cfg.AZURE_OPENAI_API_KEY,
        temperature=0
    )
)

evaluation_dataset = EvaluationDataset.from_pandas(dataset_synth.to_pandas())

# Configuración personalizada
custom_run_config = RunConfig(timeout=360)

# Ejecutar evaluación
result = evaluate(
    experiment_name='kitsune-demo-project-ragas-evaluations',
    dataset=evaluation_dataset,
    metrics=[
        LLMContextRecall(llm=evaluator_llm), 
        FactualCorrectness(llm=evaluator_llm), 
        ContextEntityRecall(llm=evaluator_llm), 
        NoiseSensitivity(llm=evaluator_llm)
    ],
    run_config=custom_run_config
)

result

Evaluating:   0%|          | 0/48 [00:00<?, ?it/s]

INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 60.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 60.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 59.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 59.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 59.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 59.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 59.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 59.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 58.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 58.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 57.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 57.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 56.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 56.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 44.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 40.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 59.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 59.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 59.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 59.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 58.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 58.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 58.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 57.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 56.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 56.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 56.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 56.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 56.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 55.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 55.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 52.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 59.000000 seconds
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://inari-yomeru.openai.azure.com/openai/deployments/inari-yomeru-gpt-4.1/chat/completions?api-version=2024-12-01-preview "HTTP/1.1 429 Too Many Requests"
INFO:openai._base_client:Retrying request to /chat/completions in 60.000000 seconds

{'context_recall': 0.0238, 'factual_correctness(mode=f1)': 0.3125, 'context_entity_recall': 0.0488, 'noise_sensitivity(mode=relevant)': 0.0000}